# hexo-theme-indigo
# https://github.com/vaycent/vaycent.github.io

#添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: Home
    url: /
  archives:
    url: /archives
#  tags:
#    url: /tags
  github:
    url: https://github.com/vaycent
    target: _blank

  stack-overflow:
    url: http://stackoverflow.com/users/6698986/vaycent
    target: _blank

  linkedin:
    url: https://www.linkedin.com/in/vaycent
    target: _blank

  book:
    text: Douban Reading
    url: https://book.douban.com/people/vaycentsun/collect?sort=title&start=0&filter=all&mode=list&tags_sort=name
    target: _blank
	
  steam:
    url: http://steamcommunity.com/id/vaycentsun
    target: _blank




#  weibo:
#    url: false
#    target: _blank

#  link:
#    text: Test
#    url: /404

rss: /atom.xml

#你的头像url
avatar: /img/avatar.png

# email
email: vaycentsun@gmail.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# Content
tags:
  title: Tags

# 文章截断
excerpt_length: 200
excerpt_link: Read more…
mathjax: false
archive_yearly: true

#是否开启分享
share: false

#是否开启搜索
search: true

#是否大屏幕下文章页隐藏导航
hideMenu: true

#是否开启toc
#toc: true
toc:
  list_number: false  # 是否显示数字排序

#站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# Miscellaneous
google_analytics: UA-82643205-1
favicon: /favicon.ico

# less
less:
  paths:
    - source/css/style.less

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo:



